kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: verdaccio
  namespace: verdaccio
spec:
  storageClassName: default
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

